name: "Deploy PRs to S3"
author: "Broken Hands"
description: "Automatically deploy built PR bundles to an S3 static website and set up deployments for each PR."
branding:
  icon: "cloud"
  color: "orange"
inputs:
  bucket-prefix:
    description: "Prefix of the bucket name. The PR number will be appended to this value."
    required: true
  bucket-region:
    description: "Region of the S3 bucket."
    required: true
  folder-to-copy:
    description: "Folder to copy assets from into S3."
    required: false
  environment-prefix:
    description: "Prefix of the GitHub Deployment Environment. The PR number will be appended to this value."
    required: false
  index-document:
    description: "Index document for the S3 bucket. Defaults to index.html."
    required: false
  error-document:
    description: "Error document for the S3 bucket. Defaults to error.html."
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
